config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tasks do
    resources :list_items, except: [:index, :show]
  end

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list_item.rb
class ListItem < ApplicationRecord
  belongs_to :task, inverse_of: :list_items

  validates :task, :description, :priority, presence: true
  validates :priority, numericality: { only_integer: true, greater_than: 0 }
  validates :complete, inclusion: { in: [true, false] }

  default_scope { order(priority: :asc) }
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user, inverse_of: :tasks

  has_many :list_items, inverse_of: :task, dependent: :destroy

  validates :name, :user, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tasks, inverse_of: :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render 'home/index'
  end
end

app/controllers/list_items_controller.rb
class ListItemsController < ApplicationController
  before_action :authenticate_user!

  def new
    task = current_user.tasks.where(id: params[:task_id]).first
    list_item = task.list_items.new

    render 'list_items/new', locals: { list_item: list_item }
  end

  def create
    task = current_user.tasks.where(id: params[:task_id]).first
    list_item = task.list_items.new(list_item_params)

    if list_item.save
      redirect_to task_path(list_item.task)
    else
      flash.now[:error] = "There was an error saving your list item. Please review the form and try again"
      render 'list_items/new', locals: { list_item: list_item }
    end
  end

  def edit
    task = current_user.tasks.where(id: params[:task_id]).first
    list_item = task.list_items.where(id: params[:id]).first

    render 'list_items/edit', locals: { list_item: list_item }
  end

  def update
    task = current_user.tasks.where(id: params[:task_id]).first
    list_item = task.list_items.where(id: params[:id]).first

    if list_item.update_attributes(list_item_params)
      redirect_to task_path(list_item.task)
    else
      flash.now[:error] = "There was an error saving your list item. Please review the form and try again"
      render 'list_items/edit', locals: { list_item: list_item }
    end
  end

  def destroy
    task = current_user.tasks.where(id: params[:task_id]).first
    list_item = task.list_items.where(id: params[:id]).first

    task = list_item.task

    if !list_item.destroy
      flash[:error] = "There was an error destroying your list item. Please try again"
    end

    redirect_to task_path(task)
  end

  private

  def list_item_params
    params.require(:list_item).permit(:description, :priority, :complete)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!

  def index
    tasks = current_user.tasks.includes(:list_items)

    render 'tasks/index', locals: { tasks: tasks }
  end

  def show
    task = current_user.tasks.find_by(id: params[:id])

    render 'tasks/show', locals: { task: task }
  end

  def new
    task = current_user.tasks.new

    render 'tasks/new', locals: { task: task }
  end

  def create
    task = current_user.tasks.new(task_params)

    if task.save
      redirect_to task_path(task)
    else
      flash.now[:error] = "There was an error saving your task. Please review the form and try again"
      render 'tasks/new', locals: { task: task }
    end
  end

  def edit
    task = current_user.tasks.find_by(id: params[:id])

    render 'tasks/edit', locals: { task: task }
  end

  def update
    task = current_user.tasks.find_by(id: params[:id])

    if task.update_attributes(task_params)
      redirect_to task_path(task)
    else
      flash.now[:error] = "There was an error saving your task. Please review the form and try again"
      render 'tasks/edit', locals: { task: task }
    end
  end

  def destroy
    task = current_user.tasks.find_by(id: params[:id])

    if !task.destroy
      flash[:error] = "There was an error destroying your task. Please try again"
    end

    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when 'notice' then "alert alert-info"
    when 'success' then "alert alert-success"
    when 'error' then "alert alert-danger"
    when 'alert' then "alert alert-warning"
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <%#= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href=<%=root_path%>>ToDo</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href=<%=tasks_path%>>Tasks</a>
          </li>
          <li class="nav-item">
            <% if current_user %>
              <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
            <% else %>
              <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
            <% end %>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container-fluid">
      <div class="row">
        <div class="col-12">
          <%flash.each do |key, value| %>
            <div class="<%=flash_class(key) %>">
              <%= value %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/list_items/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 mt-5 mb-5">
      <h1>
        Edit List Item
      </h1>
    </div>
    <div class="col-12">
      <%= form_for list_item, url: task_list_item_path(list_item.task, list_item), method: :patch do |f| %>
        <div class="form-group">
          <%= f.text_field :description, placeholder: "Description", class: "w-100" %>
        </div>
        <div class="form-group">
          <%= f.text_field :priority, placeholder: "Priority (Integer Greater Than Zero)", class: "w-100" %>
        </div>
        <div class="form-check">
          <%= f.check_box :complete, class: "form-check-input", id: "completeCheck" %>
          <label class="form-check-label" for="completeCheck">
            Complete?
          </label>
        </div>
        <%= f.submit "Update", class: "btn btn-lg btn-primary mt-3" %>
      <% end %>
    </div>
  </div>
</div>

app/views/list_items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 mt-5 mb-5">
      <h1>
        New List Item
      </h1>
    </div>
    <div class="col-12">
      <%= form_for list_item, url: task_list_items_path(list_item.task) do |f| %>
        <div class="form-group">
          <%= f.text_field :description, placeholder: "Description", class: "w-100" %>
        </div>
        <div class="form-group">
          <%= f.text_field :priority, placeholder: "Priority (Integer Greater Than Zero)", class: "w-100" %>
        </div>
        <%= f.submit "Submit", class: "btn btn-lg btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 mt-5 mb-5">
      <h1>
        Edit Task
      </h1>
    </div>
    <div class="col-12">
      <%= form_for task do |f| %>
        <div class="form-group">
          <%= f.text_field :name, placeholder: "Task Name", class: "w-100" %>
        </div>
        <%= f.submit "Update", class: "btn btn-lg btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 mt-5 mb-2">
      <%= link_to "New Task", new_task_path, class: "btn btn-lg btn-secondary" %>
    </div>
    <div class="col-12">
      <table class="table table-sm table-borderless table-responsive-sm">
        <% tasks.each do |task| %>
          <tr class="border">
            <td>
              <%= task.name %>
            </td>
            <td>
              <%= task.list_items.count %> List Item(s)
            </td>
            <td>
              <%= link_to "Edit", edit_task_path(task), class: "btn btn-sm btn-primary" %>
              <%= link_to "Show", task_path(task), class: "btn btn-sm btn-success" %>
              <%= link_to "Delete", task_path(task), method: :delete, class: "btn btn-sm btn-danger" %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 mt-5 mb-5">
      <h1>
        New Task
      </h1>
    </div>
    <div class="col-12">
      <%= form_for task do |f| %>
        <div class="form-group">
          <%= f.text_field :name, placeholder: "Task Name", class: "w-100" %>
        </div>
        <%= f.submit "Submit", class: "btn btn-lg btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 mt-5 mb-5">
      <h1>
        <%= task.name %>
      </h1>
    </div>
    <div class="col-12">
      <h3>
        List Items
      </h3>
      <div class="col-12 mt-3 mb-2">
        <%= link_to "New List Item", new_task_list_item_path(task), class: "btn btn-lg btn-secondary" %>
      </div>
      <div class="col-12">
        <table class="table table-sm table-borderless table-responsive-sm">
          <thead>
            <tr>
              <th scope="col">Description</th>
              <th scope="col">Priority</th>
              <th scope="col">Complete?</th>
              <th scope="col"></th>
            </tr>
          </thead>
          <% task.list_items.each do |list_item| %>
            <tr class="border">
              <td>
                <%= list_item.description %>
              </td>
              <td>
                <%= list_item.priority %>
              </td>
              <td>
                <%= list_item.complete ? "Yes" : "No" %>
              </td>
              <td>
                <%= link_to "Edit", edit_task_list_item_path(task, list_item), class: "btn btn-sm btn-primary" %>
                <%= link_to "Delete", task_list_item_path(task, list_item), method: :delete, class: "btn btn-sm btn-danger" %>
              </td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>